#name: Code Analysis
#
#on: [pull_request]
#
#jobs:
#  analyze-code:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Run Code Analysis
#        run: |
#          # Your code analysis command goes here
#
#      - name: Add Annotations
#        uses: actions/github-script@v6
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const annotations = [
#              {
#                path: 'path/to/file.js',
#                start_line: 10,
#                end_line: 10,
#                annotation_level: 'failure',
#                title: 'Linting Issue',
#                message: 'There is a linting issue on this line.',
#              },
#            ];
#
#            for (const annotation of annotations) {
#              github.rest.pulls.createReview({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                pull_number: context.payload.pull_request.number,
#                body: annotation.message,
#                event: 'COMMENT',
#              });
#
#              github.rest.checks.create({
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                name: 'Code Analysis',
#                head_sha: context.sha,
#                conclusion: 'failure',
#                output: {
#                  title: annotation.title,
#                  summary: annotation.message,
#                  annotations: [annotation],
#                },
#              });
#            }


name: Add Annotations

on: [pull_request]

jobs:
  add-annotations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fix EOF Newline
        uses: gps/newline-at-eof@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_AND_PUSH_CHANGES: false


      # - name: Run Code Analysis
      #   run: |
      #     # Your code analysis command goes here

      # - name: Add Annotations
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       const annotations = [
      #         {
      #           path: 'path/to/file.js',
      #           start_line: 10,
      #           end_line: 10,
      #           annotation_level: 'failure',
      #           title: 'Linting Issue',
      #           message: 'There is a linting issue on this line.',
      #         },
      #       ];

      #       for (const annotation of annotations) {
      #         github.rest.pulls.createReview({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           pull_number: context.payload.pull_request.number,
      #           body: annotation.message,
      #           event: 'COMMENT',
      #         });

      #         github.rest.checks.create({
      #           owner: context.repo.owner,
      #           repo: context.repo.repo,
      #           name: 'Code Analysis',
      #           head_sha: context.sha,
      #           conclusion: 'failure',
      #           output: {
      #             title: annotation.title,
      #             summary: annotation.message,
      #             annotations: [annotation],
      #           },
      #         });
      #       }

