name: Release
on:
  push:
    branches:
      - main
jobs:
  Release:
    runs-on: [self-hosted, release]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."