name: Release

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build JAR
        run: 'gradle :main:shadowJar'

      - name: Determine next version
        uses: gps/determine-next-version@master
        id: next_version
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag commit
        uses: gps/tag_commit@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{steps.next_version.outputs.NEXT_BUILD_VERSION}}

      - name: Create Github Release
        id: create-new-release
        uses: gps/create-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
          release_name: Release v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: main/build/libs/EagleGen-main.jar
          asset_name: EagleGen-main.jar
          asset_content_type: application/jar