name: Release

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: gps/create-github-release@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
