name: Release

on:
  workflow_dispatch
#  pull_request_target:
#    types:
#      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: 'gradle :main:shadowJar'

      - name: Determine next version
        uses: gps/determine-next-version@master
        id: next_version
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag commit
        uses: gps/tag-commit@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{steps.next_version.outputs.NEXT_BUILD_VERSION}}

      - name: Create release
        uses: gps/create-github-release@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
          ARTIFACTS: |
            main/build/libs/EagleGen-main.jar ==> EagleGen.jar
