name: Release

on:
  pull_request_target:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

#      - name: Find Latest Release Tag
#        id: latest_tag_name
#        run: |
#          git describe --abbrev=0 --tags

      - name: Determine next version
        uses: gps/determine-next-version@master
        id: next_version
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}
          release_name: Release v${{steps.next_version.outputs.NEXT_BUILD_VERSION}}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./build/libs/Eagle-Gen-0.0.1.jar
          asset_name: site-v${{ steps.create-new-release.outputs.upload_url }}
          asset_content_type: application/jar