name: Test Create server

env:
  HCLOUD_TOKEN: sample_token
on:
  workflow_dispatch
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Add hcloud library
        run: pip install hcloud
      - name: Create servers
        run: python ./python-scripts/create-ephemeral-servers.py
