name: Test Create server
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Homebrew Prerequisites
        run: sudo apt-get install build-essential procps curl file git
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Set PATH for brew
        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
