name: Test Create server
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      - name: Install Homebrew Prerequisites
#        run: sudo apt-get install build-essential procps curl file git
#      - name: Install Homebrew
#        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#      - name: Set PATH for brew
#        run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
#      - name: Set Token
#        run: export HCLOUD_TOKEN=secrets.HETZNER_TOKEN
#      - name: Install hcloud via brew
#        run: brew install hcloud
#      - name: Create Server
#        run: hcloud create context test-project
      - name: print working directory
        run: ls
      - name: read configuration.json
        run: |
          echo 'CONFIGURATION_JSON<<EOF' >> $GITHUB_ENV
          cat configuration.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Show contents of configuration.json
        run: |
          echo '${{ fromJson(env.CONFIGURATION_JSON).ephemeral }}'
